Jobs: 1000
Script: /u/ey/ntran/ldmx/dev/scripting/ldmx-sw-scripts/production/run_ecal_muon.py
Output: ntran_4pt0_gev_e_ecal_muon_v3_magnet_20170928
Detector: ldmx-det-full-v3-fieldmap-magnet
Path: /u/ey/ntran/ldmx/dev/scripting/ldmx-sw-scripts/prod_ecal_muon_20170928_1
#EnvScript: /u/ey/ntran/ldmx/dev/scripting/ldmx-sw-scripts/production/setupForMuons.sh
EnvScript: /u/ey/ntran/ldmx/dev/muons/officialv3/ldmx-sw/install/bin/ldmx-setup-env.sh 